language: python
python:
  - 2.6
  - 2.7
sudo: false
cache:
  directories:
    - eggs
env:
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
matrix:
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3
    - python: 2.6
      env: PLONE_VERSION=5.0
    - python: 2.6
      env: PLONE_VERSION=5.1
  fast_finish: true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - pip install zc.buildout
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q
branches:
  only:
    - master
script:
  - bin/code-analysis
  - bin/test
notifications:
  irc: irc.freenode.org#propertyshelf
  hipchat:
    secure: "T3yulcr/ngJczd1bac/GuB2GxhOXHND0KcajFkj9ULxmL1WQBGlMJJJkUDEAzTBouZ8JW2WbDdV80GxnQ592tFyGfABEWxNM3cKw8dFh6CWMDZkhS+W60wryFMnvxH1aoHJZKCt6/i/Dhg1bYBj1q27W93q7rCeNo1w5+v6I3MY="
